import { v } from "convex/values";
import type { Infer } from "convex/values";
import { internal } from "./_generated/api";
import type { Doc, Id } from "./_generated/dataModel";
import {
  internalAction,
  internalMutation,
  internalQuery,
  mutation,
  query,
} from "./_generated/server";
import type { MutationCtx, QueryCtx } from "./_generated/server";
import { requireParent } from "./lib/auth";
import { addDays, berlinHour, compareDates, todayBerlin } from "./lib/dates";
import { holidaysBetween } from "./lib/holidays";
import {
  AUTO_RUN_HOURS,
  FAMILY_WHO,
  SYSTEM_INSTRUCTION,
  briefingKindForHour,
  buildPrompt,
  extractCandidateText,
  parseBriefingResponse,
  responseSchema,
  type BriefingContext,
  type BriefingKind,
  type ContextTask,
} from "./lib/parentBriefing";
import { isDoneToday, isOverdueForToday } from "./lib/todos";
import { parentBriefingItemValidator } from "./lib/validators";

// Parents' briefing, generated by the Family App via Gemini — independent of
// the dashboard briefings in `briefings`. Parents trigger a new one from the
// Overview; the hourly cron creates one at AUTO_RUN_HOURS (Berlin).
//
// Env vars (`npx convex env set`):
// - GEMINI_API_KEY — required; without it attempts end with a clear error.
// - GEMINI_MODEL — optional model id, defaults to DEFAULT_MODEL.

const DEFAULT_MODEL = "gemini-3.8-flash";
const GEMINI_ENDPOINT = "https://generativelanguage.googleapis.com/v1beta/models";
const GEMINI_TIMEOUT_MS = 60_000;

// A "generating" row older than this is treated as failed (action crashed).
const STALE_GENERATING_MS = 3 * 60_000;
// Manual regenerations per Berlin day (cost guard).
const MANUAL_DAILY_LIMIT = 20;
const RETENTION_DAYS = 14;
// Dashboard data older than this is flagged in the prompt (PLAN §7).
const SNAPSHOT_STALE_MS = 2 * 60 * 60_000;
const HOMEWORK_WINDOW_DAYS = 3;
const EXAM_WINDOW_DAYS = 7;

const resolvedItemValidator = v.object({
  who: v.union(v.string(), v.null()),
  color: v.union(v.string(), v.null()),
  emoji: v.string(),
  text: v.string(),
});

const briefingViewValidator = v.object({
  date: v.string(),
  kind: v.union(v.literal("morning"), v.literal("evening")),
  trigger: v.union(v.literal("manual"), v.literal("auto")),
  requestedByName: v.union(v.string(), v.null()),
  generatedAt: v.number(),
  headline: v.string(),
  summary: v.string(),
  today: v.array(resolvedItemValidator),
  ahead: v.array(resolvedItemValidator),
});

type ResolvedItem = Infer<typeof resolvedItemValidator>;

async function recentRows(
  ctx: { db: QueryCtx["db"] },
  limit: number,
): Promise<Doc<"parentBriefings">[]> {
  return await ctx.db
    .query("parentBriefings")
    .withIndex("by_requestedAt")
    .order("desc")
    .take(limit);
}

function isFreshGenerating(row: Doc<"parentBriefings">, now: number): boolean {
  return row.status === "generating" && now - row.requestedAt < STALE_GENERATING_MS;
}

// Overview card data: the newest finished briefing plus the state of the
// newest attempt (running / failed). Parents only.
export const latest = query({
  args: { token: v.string() },
  returns: v.object({
    briefing: v.union(briefingViewValidator, v.null()),
    generating: v.boolean(),
    error: v.union(v.string(), v.null()),
  }),
  handler: async (ctx, args) => {
    await requireParent(ctx, args.token);
    const now = Date.now();
    const rows = await recentRows(ctx, 25);
    const newest = rows[0];
    const shown = rows.find((row) => row.status === "ready");

    let error: string | null = null;
    if (newest !== undefined && newest !== shown) {
      if (newest.status === "error") {
        error = newest.error ?? "Die Zusammenfassung konnte nicht erstellt werden.";
      } else if (newest.status === "generating" && !isFreshGenerating(newest, now)) {
        error = "Die Erstellung hat zu lange gedauert. Bitte erneut versuchen.";
      }
    }

    if (shown === undefined) {
      return {
        briefing: null,
        generating: newest !== undefined && isFreshGenerating(newest, now),
        error,
      };
    }

    const users = await ctx.db.query("users").collect();
    const bySlug = new Map(users.map((user) => [user.slug, user]));
    const resolve = (item: Infer<typeof parentBriefingItemValidator>): ResolvedItem => {
      const user = item.who === FAMILY_WHO ? undefined : bySlug.get(item.who);
      return {
        who: user?.name ?? null,
        color: user?.color ?? null,
        emoji: item.emoji,
        text: item.text,
      };
    };
    const requester =
      shown.requestedBy === undefined ? null : await ctx.db.get(shown.requestedBy);

    return {
      briefing: {
        date: shown.date,
        kind: shown.kind,
        trigger: shown.trigger,
        requestedByName: requester?.name ?? null,
        generatedAt: shown.generatedAt ?? shown.requestedAt,
        headline: shown.headline ?? "",
        summary: shown.summary ?? "",
        today: (shown.today ?? []).map(resolve),
        ahead: (shown.ahead ?? []).map(resolve),
      },
      generating: newest !== undefined && isFreshGenerating(newest, now),
      error,
    };
  },
});

// Insert a "generating" row and schedule the Gemini call.
async function startRun(
  ctx: MutationCtx,
  trigger: "manual" | "auto",
  requestedBy: Id<"users"> | undefined,
  now: number,
): Promise<void> {
  const kind: BriefingKind = briefingKindForHour(berlinHour(now));
  const briefingId = await ctx.db.insert("parentBriefings", {
    date: todayBerlin(now),
    kind,
    trigger,
    requestedBy,
    requestedAt: now,
    status: "generating",
  });
  await ctx.scheduler.runAfter(0, internal.parentBriefing.generate, {
    briefingId,
    kind,
  });
}

// "Neu erstellen" on the Overview. Parents only; no-op while one is running.
export const request = mutation({
  args: { token: v.string() },
  returns: v.object({
    started: v.boolean(),
    reason: v.union(v.literal("running"), v.literal("limit"), v.null()),
  }),
  handler: async (ctx, args) => {
    const user = await requireParent(ctx, args.token);
    const now = Date.now();
    const rows = await recentRows(ctx, 60);
    if (rows[0] !== undefined && isFreshGenerating(rows[0], now)) {
      return { started: false, reason: "running" as const };
    }
    const today = todayBerlin(now);
    const manualToday = rows.filter(
      (row) => row.trigger === "manual" && row.date === today,
    ).length;
    if (manualToday >= MANUAL_DAILY_LIMIT) {
      return { started: false, reason: "limit" as const };
    }
    await startRun(ctx, "manual", user._id, now);
    return { started: true, reason: null };
  },
});

// Hourly cron: create the automatic briefings and prune old rows.
export const autoRun = internalMutation({
  args: {},
  returns: v.object({ started: v.boolean(), deleted: v.number() }),
  handler: async (ctx) => {
    const now = Date.now();
    let started = false;
    if (AUTO_RUN_HOURS.includes(berlinHour(now))) {
      const today = todayBerlin(now);
      const kind = briefingKindForHour(berlinHour(now));
      const rows = await recentRows(ctx, 60);
      const exists = rows.some(
        (row) => row.trigger === "auto" && row.date === today && row.kind === kind,
      );
      const running = rows[0] !== undefined && isFreshGenerating(rows[0], now);
      if (!exists && !running) {
        await startRun(ctx, "auto", undefined, now);
        started = true;
      }
    }

    const threshold = now - RETENTION_DAYS * 24 * 60 * 60_000;
    const old = await ctx.db
      .query("parentBriefings")
      .withIndex("by_requestedAt", (q) => q.lt("requestedAt", threshold))
      .take(100);
    for (const row of old) {
      await ctx.db.delete(row._id);
    }
    return { started, deleted: old.length };
  },
});

function berlinNowLabel(now: number): string {
  return new Intl.DateTimeFormat("de-DE", {
    timeZone: "Europe/Berlin",
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(now));
}

// Everything the prompt needs, read in one consistent snapshot.
export const collectContext = internalQuery({
  args: { kind: v.union(v.literal("morning"), v.literal("evening")) },
  handler: async (ctx, args): Promise<BriefingContext> => {
    const now = Date.now();
    const today = todayBerlin(now);
    const tomorrow = addDays(today, 1);

    const users = await ctx.db.query("users").collect();
    const byId = new Map(users.map((user) => [user._id, user]));
    const members = [...users]
      .sort(
        (a, b) =>
          (a.role === b.role ? 0 : a.role === "parent" ? -1 : 1) ||
          a.name.localeCompare(b.name, "de"),
      )
      .map((user) => ({ slug: user.slug, name: user.name, role: user.role }));

    const toTask = async (
      instance: Doc<"taskInstances">,
    ): Promise<ContextTask | null> => {
      const task = await ctx.db.get(instance.taskId);
      if (task === null || instance.status === "missed") {
        return null;
      }
      const assignee =
        instance.assigneeId === undefined ? undefined : byId.get(instance.assigneeId);
      return {
        title: task.title,
        who: assignee?.slug ?? null,
        status: instance.status,
        ...(instance.date !== undefined ? { date: instance.date } : {}),
        ...(instance.pointsSnapshot !== undefined
          ? { points: instance.pointsSnapshot }
          : {}),
      };
    };
    const collect = async (
      instances: Doc<"taskInstances">[],
    ): Promise<ContextTask[]> => {
      const result: ContextTask[] = [];
      for (const instance of instances) {
        const item = await toTask(instance);
        if (item !== null) {
          result.push(item);
        }
      }
      return result;
    };

    const datedToday = await ctx.db
      .query("taskInstances")
      .withIndex("by_date", (q) => q.eq("date", today))
      .collect();
    const doneCandidates = await ctx.db
      .query("taskInstances")
      .withIndex("by_status", (q) => q.eq("status", "done"))
      .collect();
    const doneToday = doneCandidates.filter(
      (i) =>
        i.date !== today &&
        isDoneToday({ status: i.status, completedAt: i.completedAt }, today),
    );
    const tasksToday = await collect([...datedToday, ...doneToday]);

    const datedTomorrow = await ctx.db
      .query("taskInstances")
      .withIndex("by_date", (q) => q.eq("date", tomorrow))
      .collect();
    const tasksTomorrow = await collect(
      datedTomorrow.filter((i) => i.status === "open"),
    );

    const open = await ctx.db
      .query("taskInstances")
      .withIndex("by_status", (q) => q.eq("status", "open"))
      .collect();
    const pending = await ctx.db
      .query("taskInstances")
      .withIndex("by_status", (q) => q.eq("status", "pending"))
      .collect();
    const overdueInstances: Doc<"taskInstances">[] = [];
    for (const instance of [...open, ...pending]) {
      const task = await ctx.db.get(instance.taskId);
      if (
        task !== null &&
        isOverdueForToday(
          {
            date: instance.date,
            status: instance.status,
            recurrenceKind: task.recurrence.kind,
          },
          today,
        )
      ) {
        overdueInstances.push(instance);
      }
    }
    const tasksOverdue = await collect(overdueInstances);

    const requested = await ctx.db
      .query("redemptions")
      .withIndex("by_status", (q) => q.eq("status", "requested"))
      .collect();
    const rewardRequests: { who: string; title: string }[] = [];
    for (const redemption of requested) {
      const reward = await ctx.db.get(redemption.rewardId);
      const kid = byId.get(redemption.userId);
      if (reward !== null && kid !== undefined) {
        rewardRequests.push({ who: kid.name, title: reward.title });
      }
    }

    const kids: BriefingContext["kids"] = [];
    for (const kid of users.filter((user) => user.role === "child")) {
      const snapshot = await ctx.db
        .query("childSnapshots")
        .withIndex("by_childSlug", (q) => q.eq("childSlug", kid.slug))
        .unique();
      kids.push({
        slug: kid.slug,
        name: kid.name,
        stale: snapshot === null ? false : now - snapshot.sourceUpdatedAt > SNAPSHOT_STALE_MS,
        days: (snapshot?.days ?? []).filter(
          (day) => day.date === today || day.date === tomorrow,
        ),
        homework: (snapshot?.homework ?? []).filter(
          (item) =>
            compareDates(item.dueDate, today) >= 0 &&
            compareDates(item.dueDate, addDays(today, HOMEWORK_WINDOW_DAYS)) <= 0,
        ),
        exams: (snapshot?.exams ?? []).filter(
          (exam) =>
            compareDates(exam.date, today) >= 0 &&
            compareDates(exam.date, addDays(today, EXAM_WINDOW_DAYS)) <= 0,
        ),
      });
    }
    kids.sort((a, b) => a.name.localeCompare(b.name, "de"));

    return {
      kind: args.kind,
      today,
      tomorrow,
      nowLabel: `${berlinNowLabel(now)} Uhr`,
      holidays: holidaysBetween(today, addDays(today, 7)),
      members,
      tasksToday,
      tasksOverdue,
      tasksTomorrow,
      pendingApprovals: pending.length,
      rewardRequests,
      kids,
    };
  },
});

export const finish = internalMutation({
  args: {
    briefingId: v.id("parentBriefings"),
    headline: v.string(),
    summary: v.string(),
    today: v.array(parentBriefingItemValidator),
    ahead: v.array(parentBriefingItemValidator),
    model: v.string(),
  },
  returns: v.null(),
  handler: async (ctx, { briefingId, ...result }) => {
    const row = await ctx.db.get(briefingId);
    if (row === null) {
      return null;
    }
    await ctx.db.patch(briefingId, {
      ...result,
      status: "ready",
      generatedAt: Date.now(),
      error: undefined,
    });
    return null;
  },
});

export const fail = internalMutation({
  args: { briefingId: v.id("parentBriefings"), error: v.string() },
  returns: v.null(),
  handler: async (ctx, { briefingId, error }) => {
    const row = await ctx.db.get(briefingId);
    if (row === null) {
      return null;
    }
    await ctx.db.patch(briefingId, { status: "error", error });
    return null;
  },
});

function httpErrorMessage(status: number): string {
  if (status === 400) {
    return "Die KI hat die Anfrage nicht verstanden (400). Ist GEMINI_MODEL korrekt?";
  }
  if (status === 401 || status === 403) {
    return "Der Gemini-API-Schlüssel wurde abgelehnt. Bitte GEMINI_API_KEY prüfen.";
  }
  if (status === 404) {
    return "Das Gemini-Modell wurde nicht gefunden. Bitte GEMINI_MODEL prüfen.";
  }
  if (status === 429) {
    return "Gemini-Kontingent erschöpft. Bitte später erneut versuchen.";
  }
  if (status >= 500) {
    return `Gemini ist gerade nicht erreichbar (${String(status)}). Bitte später erneut versuchen.`;
  }
  return `Gemini-Fehler (${String(status)}).`;
}

// Collect the context, call Gemini, store the result (or the error).
export const generate = internalAction({
  args: {
    briefingId: v.id("parentBriefings"),
    kind: v.union(v.literal("morning"), v.literal("evening")),
  },
  returns: v.null(),
  handler: async (ctx, { briefingId, kind }) => {
    const apiKey = process.env.GEMINI_API_KEY;
    const model = process.env.GEMINI_MODEL ?? DEFAULT_MODEL;
    try {
      if (apiKey === undefined || apiKey === "") {
        throw new Error("GEMINI_API_KEY ist in Convex nicht gesetzt.");
      }
      const context = await ctx.runQuery(internal.parentBriefing.collectContext, {
        kind,
      });
      const slugs = context.members.map((member) => member.slug);

      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), GEMINI_TIMEOUT_MS);
      let response: Response;
      try {
        response = await fetch(
          `${GEMINI_ENDPOINT}/${encodeURIComponent(model)}:generateContent`,
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "x-goog-api-key": apiKey,
            },
            body: JSON.stringify({
              systemInstruction: { parts: [{ text: SYSTEM_INSTRUCTION }] },
              contents: [{ role: "user", parts: [{ text: buildPrompt(context) }] }],
              generationConfig: {
                temperature: 0.5,
                responseMimeType: "application/json",
                responseSchema: responseSchema(slugs),
              },
            }),
            signal: controller.signal,
          },
        );
      } catch (fetchError) {
        throw new Error(
          fetchError instanceof Error && fetchError.name === "AbortError"
            ? "Gemini hat nicht rechtzeitig geantwortet."
            : "Gemini ist nicht erreichbar.",
          { cause: fetchError },
        );
      } finally {
        clearTimeout(timer);
      }

      if (!response.ok) {
        // Log the body for debugging (visible in the Convex dashboard logs);
        // it never contains the key.
        console.error("Gemini error", response.status, await response.text());
        throw new Error(httpErrorMessage(response.status));
      }

      const parsed = parseBriefingResponse(
        extractCandidateText(await response.json()),
        slugs,
      );
      await ctx.runMutation(internal.parentBriefing.finish, {
        briefingId,
        ...parsed,
        model,
      });
    } catch (error) {
      await ctx.runMutation(internal.parentBriefing.fail, {
        briefingId,
        error:
          error instanceof Error
            ? error.message
            : "Die Zusammenfassung konnte nicht erstellt werden.",
      });
    }
    return null;
  },
});
