import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { recurrenceValidator } from "./lib/recurrence";
import {
  briefingItemValidator,
  childDayValidator,
  examValidator,
  homeworkValidator,
  parentBriefingItemValidator,
} from "./lib/validators";

export default defineSchema({
  users: defineTable({
    slug: v.string(),
    name: v.string(),
    role: v.union(v.literal("parent"), v.literal("child")),
    color: v.string(),
    emoji: v.string(),
    pinHash: v.string(),
    pinSalt: v.string(),
    failedAttempts: v.number(),
    lockedUntil: v.optional(v.number()),
  }).index("by_slug", ["slug"]),

  sessions: defineTable({
    userId: v.id("users"),
    token: v.string(),
    createdAt: v.number(),
    expiresAt: v.number(),
  }).index("by_token", ["token"]),

  tasks: defineTable({
    title: v.string(),
    notes: v.optional(v.string()),
    assigneeId: v.optional(v.id("users")), // undefined = whole family
    points: v.optional(v.number()), // only when assignee is a child (enforced in Task 2)
    recurrence: recurrenceValidator, // from convex/lib/recurrence.ts
    startDate: v.string(), // YYYY-MM-DD (Berlin)
    endDate: v.optional(v.string()),
    active: v.boolean(),
    createdBy: v.id("users"),
    createdAt: v.number(),
  }).index("by_active", ["active"]),

  taskInstances: defineTable({
    taskId: v.id("tasks"),
    assigneeId: v.optional(v.id("users")),
    date: v.optional(v.string()), // undefined = undated one-off ("anytime")
    status: v.union(
      v.literal("open"),
      v.literal("pending"),
      v.literal("done"),
      v.literal("missed"),
    ),
    pointsSnapshot: v.optional(v.number()),
    completedBy: v.optional(v.id("users")),
    completedAt: v.optional(v.number()),
    reviewedBy: v.optional(v.id("users")),
    reviewedAt: v.optional(v.number()),
    rejectNote: v.optional(v.string()),
  })
    .index("by_task", ["taskId"])
    .index("by_task_date", ["taskId", "date"])
    .index("by_assignee_date", ["assigneeId", "date"])
    .index("by_status", ["status"])
    .index("by_date", ["date"]),

  pointTransactions: defineTable({
    userId: v.id("users"),
    delta: v.number(), // + for tasks/bonus, − for rewards/penalty
    reason: v.union(
      v.literal("task"),
      v.literal("reward"),
      v.literal("manual"),
    ),
    refId: v.optional(v.string()), // instance id (reason "task"); redemption id
    note: v.optional(v.string()),
    createdBy: v.id("users"),
    createdAt: v.number(),
  }).index("by_user", ["userId"]),

  // Reward catalog (tiny table; full collect + sort by title, no index).
  rewards: defineTable({
    title: v.string(),
    emoji: v.optional(v.string()),
    cost: v.number(), // integer >= 1 (enforced in mutations)
    active: v.boolean(),
  }),

  redemptions: defineTable({
    rewardId: v.id("rewards"),
    userId: v.id("users"),
    costSnapshot: v.number(), // reward.cost at request time
    status: v.union(
      v.literal("requested"),
      v.literal("approved"),
      v.literal("rejected"),
    ),
    requestedAt: v.number(),
    reviewedBy: v.optional(v.id("users")),
    reviewedAt: v.optional(v.number()),
  })
    .index("by_user", ["userId"])
    .index("by_status", ["status"]),

  // Pushed by the wall dashboard (familydash), one doc per kid, replaced on
  // every push. Shape: .docs/FAMILY_APP.md › POST /ingest/child.
  childSnapshots: defineTable({
    childSlug: v.string(),
    days: v.array(childDayValidator), // today … today+6, always 7
    homework: v.array(homeworkValidator),
    exams: v.array(examValidator),
    sourceUpdatedAt: v.number(), // oldest fetch time of the sources behind it
    receivedAt: v.number(), // backend receive time
  }).index("by_childSlug", ["childSlug"]),

  // AI/rule-based briefings pushed by the dashboard; cleaned up after 14 days.
  // Shape: .docs/FAMILY_APP.md › POST /ingest/briefing.
  briefings: defineTable({
    kind: v.union(v.literal("morning"), v.literal("evening")),
    date: v.string(),
    text: v.string(),
    headline: v.optional(v.string()),
    items: v.array(briefingItemValidator),
    ai: v.boolean(),
    generatedAt: v.number(),
    receivedAt: v.number(),
  }).index("by_date_kind", ["date", "kind"]),

  // Parents' briefing generated by the Family App itself via Gemini
  // (convex/parentBriefing.ts), independent of the dashboard's `briefings`.
  // One row per attempt; the newest "ready" row is shown. Pruned after 14 days.
  parentBriefings: defineTable({
    date: v.string(), // Berlin day the briefing is about (request day)
    kind: v.union(v.literal("morning"), v.literal("evening")),
    trigger: v.union(v.literal("manual"), v.literal("auto")),
    requestedBy: v.optional(v.id("users")),
    requestedAt: v.number(),
    status: v.union(
      v.literal("generating"),
      v.literal("ready"),
      v.literal("error"),
    ),
    generatedAt: v.optional(v.number()),
    headline: v.optional(v.string()),
    summary: v.optional(v.string()),
    today: v.optional(v.array(parentBriefingItemValidator)),
    ahead: v.optional(v.array(parentBriefingItemValidator)),
    model: v.optional(v.string()),
    error: v.optional(v.string()),
  })
    .index("by_requestedAt", ["requestedAt"])
    .index("by_status_requestedAt", ["status", "requestedAt"]),

  // Web Push subscriptions, one row per browser/device. Upserted by endpoint
  // via `push.subscribe`; dead endpoints (404/410) are pruned by the sender.
  pushSubscriptions: defineTable({
    userId: v.id("users"),
    endpoint: v.string(), // push service URL (unique per device+browser)
    p256dh: v.string(), // ECDH public key (base64url)
    auth: v.string(), // auth secret (base64url)
    userAgent: v.optional(v.string()), // for debugging, set at subscribe time
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_endpoint", ["endpoint"]),

  // Explicit calendar source registry (Task 1 of the calendar pilot).
  // sourceKey is the stable identity: renames and reorders keep the same
  // document (array position is never identity). New sources start disabled
  // in shadow mode; configGeneration revokes in-flight commit permission on
  // every config/mode change. Feeds are referenced by urlEnvKey only — no
  // secrets in this table; credentials stay in server-side Convex/Coolify
  // configuration. At most MAX_CALENDAR_SOURCES (20) documents.
  calendarSources: defineTable({
    sourceKey: v.string(),
    name: v.string(),
    color: v.string(),
    panel: v.union(v.literal("column"), v.literal("school")),
    order: v.number(),
    intoCalendarId: v.optional(v.id("calendarSources")),
    personIds: v.array(v.id("users")),
    urlEnvKey: v.string(),
    enabled: v.boolean(),
    mode: v.union(
      v.literal("shadow"),
      v.literal("convex"),
      v.literal("local"),
    ),
    intervalMs: v.number(),
    configGeneration: v.number(),
    nextAttemptAt: v.optional(v.number()),
    runningImportId: v.optional(v.id("calendarImports")),
    leaseExpiresAt: v.optional(v.number()),
    publishedImportId: v.optional(v.id("calendarImports")),
    publishedDataImportId: v.optional(v.id("calendarImports")),
  })
    .index("by_sourceKey", ["sourceKey"])
    .index("by_enabled_mode_nextAttempt", [
      "enabled",
      "mode",
      "nextAttemptAt",
    ]),

  // One row per import execution. configGeneration pins the source's
  // configGeneration at start; the commit (later task) only accepts
  // configGeneration === current generation, so config/mode changes revoke
  // in-flight runs. Only a "ready" import covering the declared window
  // counts as a successful current stand for its range. No URLs or tokens.
  calendarImports: defineTable({
    sourceId: v.id("calendarSources"),
    sequence: v.number(),
    configGeneration: v.number(),
    state: v.union(
      v.literal("running"),
      v.literal("staging"),
      v.literal("ready"),
      v.literal("error"),
      v.literal("superseded"),
    ),
    fromDate: v.string(), // YYYY-MM-DD Berlin, inclusive
    toDate: v.string(), // YYYY-MM-DD Berlin, exclusive
    startedAt: v.number(),
    leaseExpiresAt: v.optional(v.number()),
    successAt: v.optional(v.number()),
    eventCount: v.optional(v.number()),
    batchCount: v.optional(v.number()),
    batchTotal: v.optional(v.number()),
    contentFingerprint: v.optional(v.string()),
    error: v.optional(v.string()), // sanitized, safe for parent UI
  })
    .index("by_source_sequence", ["sourceId", "sequence"])
    .index("by_state_lease", ["state", "leaseExpiresAt"]),

  // Normalized calendar events, stored per source. key is
  // occurrenceKey(uid, recurrenceId); the same UID in different calendars
  // stays distinct via the leading sourceId (no global uniqueness).
  // importId points at the import run that staged the event.
  calendarEvents: defineTable({
    sourceId: v.id("calendarSources"),
    importId: v.id("calendarImports"),
    key: v.string(),
    uid: v.string(),
    recurrenceId: v.optional(v.string()),
    identityQuality: v.union(
      v.literal("provider"),
      v.literal("fallback"),
    ),
    title: v.string(),
    location: v.optional(v.string()),
    startMs: v.number(),
    endMs: v.number(),
    allDay: v.boolean(),
    timezone: v.string(),
    startDate: v.optional(v.string()),
    endDate: v.optional(v.string()),
  })
    .index("by_source_import_key", ["sourceId", "importId", "key"])
    .index("by_import_start", ["importId", "startMs"]),

  // Explicit person/source bindings (no first-name guessing). The pair
  // (kind, externalId) is unique: ambiguous mappings surface as
  // configuration errors instead of auto-linking.
  personSourceBindings: defineTable({
    userId: v.id("users"),
    kind: v.union(v.literal("besteschule"), v.literal("timetable")),
    externalId: v.string(),
  })
    .index("by_kind_externalId", ["kind", "externalId"])
    .index("by_user", ["userId"]),

  // Single-family backend settings. Key "calendars" carries the global
  // configuration revision (served as CalendarFeedV1.configurationRevision),
  // the explicit setup flag (missing doc or configured=false means not set
  // up; a deliberately empty configuration has configured=true) and the
  // central Berlin day advanced by the dispatcher.
  familyBackendSettings: defineTable({
    key: v.string(),
    configurationRevision: v.number(),
    configured: v.boolean(),
    berlinDate: v.string(),
    updatedAt: v.number(),
  }).index("by_key", ["key"]),
});
