// Parents' AI briefing: context shape, prompt, Gemini response schema and a
// defensive parser (pure; no Convex imports, unit-tested).
//
// The briefing is generated by the Family App itself (not the wall dashboard):
// convex/parentBriefing.ts collects the context below, sends the prompt to
// Gemini and stores the parsed result.

import type { ChildDay, Exam, Homework } from "./validators";
import type { Holiday } from "./holidays";

export type BriefingKind = "morning" | "evening";

// From this Berlin hour on, briefings look at the rest of today + tomorrow.
export const EVENING_FROM_HOUR = 14;

// Berlin hours at which the cron creates a briefing automatically.
export const AUTO_RUN_HOURS: readonly number[] = [6, 16];

// Max items per section kept from the model output.
export const MAX_ITEMS = 6;

export const FAMILY_WHO = "familie";

export function briefingKindForHour(hour: number): BriefingKind {
  return hour < EVENING_FROM_HOUR ? "morning" : "evening";
}

export type ContextMember = {
  slug: string;
  name: string;
  role: "parent" | "child";
};

export type ContextTask = {
  title: string;
  /** Assignee slug, or null for family-wide tasks. */
  who: string | null;
  status: "open" | "pending" | "done";
  date?: string;
  points?: number;
};

export type ContextKid = {
  slug: string;
  name: string;
  /** True when the dashboard data is older than 2 hours. */
  stale: boolean;
  /** Today and tomorrow (fewer when the snapshot is shorter). */
  days: ChildDay[];
  homework: Homework[];
  exams: Exam[];
};

export type BriefingContext = {
  kind: BriefingKind;
  today: string;
  tomorrow: string;
  /** "Samstag, 3. Oktober 2026, 14:59 Uhr" */
  nowLabel: string;
  holidays: Holiday[];
  members: ContextMember[];
  tasksToday: ContextTask[];
  tasksOverdue: ContextTask[];
  tasksTomorrow: ContextTask[];
  pendingApprovals: number;
  rewardRequests: { who: string; title: string }[];
  kids: ContextKid[];
};

export type BriefingItem = { who: string; emoji: string; text: string };

export type ParsedBriefing = {
  headline: string;
  summary: string;
  today: BriefingItem[];
  ahead: BriefingItem[];
};

export const SYSTEM_INSTRUCTION = [
  "Du schreibst das tägliche Familien-Briefing für die Eltern einer Familie in Sachsen.",
  "Schreibe auf Deutsch, warm, knapp und konkret – wie eine gut organisierte Freundin, nicht wie ein Bericht.",
  "Nutze ausschließlich die Fakten aus den Daten. Erfinde nichts: keine Termine, Feiertage, Wetter, Ferien oder Gründe.",
  "Kein Markdown, keine Sternchen, keine Aufzählungszeichen im Text. Emojis nur im Feld emoji (genau ein Emoji pro Punkt).",
  "headline: höchstens 60 Zeichen, das Wichtigste des Tages.",
  "summary: 1–2 Sätze Überblick, was heute (bzw. abends: noch heute und morgen) zählt.",
  "today: konkrete Punkte für heute, wichtigste zuerst (Stundenplan-Änderungen, Termine, offene oder überfällige Aufgaben, Freigaben, fehlendes Essen).",
  "ahead: Vorausschau auf morgen und die nächsten Tage (Arbeiten, fällige Hausaufgaben, Termine, Feiertage).",
  `Jeder Punkt: ein kurzer Satz, höchstens 110 Zeichen. who ist der slug der betroffenen Person oder "${FAMILY_WHO}". Höchstens ${String(MAX_ITEMS)} Punkte pro Abschnitt.`,
  "Wiederhole die headline nicht in summary. Nenne Uhrzeiten im Format 14:30. Fasse Gleichartiges zusammen statt aufzuzählen.",
  "Wenn Daten veraltet markiert sind, weise kurz darauf hin. Wenn wenig los ist, sag das ehrlich und kurz.",
].join("\n");

function taskLine(task: ContextTask, members: ContextMember[]): string {
  const who =
    task.who === null
      ? "Familie"
      : (members.find((member) => member.slug === task.who)?.name ?? task.who);
  const status =
    task.status === "done"
      ? "erledigt"
      : task.status === "pending"
        ? "erledigt, wartet auf Freigabe"
        : "offen";
  const parts = [`${task.title} (${who}, ${status}`];
  if (task.date !== undefined) {
    parts.push(`, fällig ${task.date}`);
  }
  if (task.points !== undefined) {
    parts.push(`, ${String(task.points)} Punkte`);
  }
  return `- ${parts.join("")})`;
}

function dayBlock(day: ChildDay): string[] {
  const lines: string[] = [`  ${day.date}:`];
  if (day.notices !== undefined && day.notices.length > 0) {
    lines.push(`    Hinweise: ${day.notices.join(" | ")}`);
  }
  if (day.timetable.length === 0) {
    lines.push("    Stundenplan: kein Unterricht");
  } else {
    const first = day.timetable.find((lesson) => lesson.start !== undefined);
    const last = [...day.timetable]
      .reverse()
      .find((lesson) => lesson.end !== undefined);
    lines.push(
      `    Unterricht: ${String(day.timetable.length)} Stunden${
        first?.start !== undefined ? `, ab ${first.start}` : ""
      }${last?.end !== undefined ? `, bis ${last.end}` : ""}`,
    );
    for (const lesson of day.timetable) {
      if (lesson.change !== undefined) {
        lines.push(
          `    Änderung: ${lesson.subject}${
            lesson.start !== undefined ? ` (${lesson.start})` : ""
          } – ${lesson.change.type}${
            lesson.change.note !== undefined ? `: ${lesson.change.note}` : ""
          }`,
        );
      }
    }
  }
  for (const event of day.events) {
    lines.push(
      `    Termin: ${event.title}${
        event.allDay ? " (ganztägig)" : ` (${event.start})`
      }${event.location !== undefined ? `, ${event.location}` : ""}`,
    );
  }
  if (day.meal !== undefined) {
    lines.push(
      day.meal.ordered
        ? `    Mittagessen: ${day.meal.title ?? "bestellt"}`
        : "    Mittagessen: NICHT bestellt",
    );
  }
  return lines;
}

/** The user prompt: all facts as compact German text. */
export function buildPrompt(context: BriefingContext): string {
  const lines: string[] = [];
  lines.push(`Jetzt: ${context.nowLabel}`);
  lines.push(
    context.kind === "morning"
      ? "Art: Morgen-Briefing – Fokus auf heute."
      : `Art: Abend-Briefing – Fokus auf den Rest von heute und auf morgen (${context.tomorrow}).`,
  );
  lines.push("");
  lines.push("Familie (slug: Name, Rolle):");
  for (const member of context.members) {
    lines.push(
      `- ${member.slug}: ${member.name}, ${member.role === "parent" ? "Elternteil" : "Kind"}`,
    );
  }

  lines.push("");
  lines.push("Feiertage in Sachsen (nächste 7 Tage):");
  if (context.holidays.length === 0) {
    lines.push("- keine");
  } else {
    for (const holiday of context.holidays) {
      lines.push(`- ${holiday.date}: ${holiday.name}`);
    }
  }

  const section = (title: string, tasks: ContextTask[]): void => {
    lines.push("");
    lines.push(`${title}:`);
    if (tasks.length === 0) {
      lines.push("- keine");
      return;
    }
    for (const task of tasks) {
      lines.push(taskLine(task, context.members));
    }
  };
  section("Aufgaben heute", context.tasksToday);
  section("Überfällige Aufgaben", context.tasksOverdue);
  section("Aufgaben morgen", context.tasksTomorrow);

  lines.push("");
  lines.push(
    `Offene Freigaben für die Eltern: ${String(context.pendingApprovals)} erledigte Aufgaben warten auf Bestätigung.`,
  );
  if (context.rewardRequests.length > 0) {
    lines.push("Belohnungswünsche der Kinder:");
    for (const request of context.rewardRequests) {
      lines.push(`- ${request.who}: ${request.title}`);
    }
  }

  for (const kid of context.kids) {
    lines.push("");
    lines.push(
      `Schule und Termine ${kid.name} (${kid.slug})${
        kid.stale ? " – ACHTUNG: Daten älter als 2 Stunden" : ""
      }:`,
    );
    if (kid.days.length === 0) {
      lines.push("  keine Daten vom Wand-Dashboard");
    }
    for (const day of kid.days) {
      lines.push(...dayBlock(day));
    }
    if (kid.homework.length > 0) {
      lines.push("  Hausaufgaben (bald fällig):");
      for (const item of kid.homework) {
        lines.push(`    - ${item.subject}, fällig ${item.dueDate}: ${item.text}`);
      }
    }
    if (kid.exams.length > 0) {
      lines.push("  Arbeiten (nächste 7 Tage):");
      for (const exam of kid.exams) {
        lines.push(
          `    - ${exam.subject} am ${exam.date}${exam.text !== undefined ? `: ${exam.text}` : ""}`,
        );
      }
    }
  }

  return lines.join("\n");
}

/** Gemini `responseSchema` (OpenAPI subset) for the structured answer. */
export function responseSchema(slugs: string[]): Record<string, unknown> {
  const item = {
    type: "OBJECT",
    properties: {
      who: { type: "STRING", enum: [...slugs, FAMILY_WHO] },
      emoji: { type: "STRING" },
      text: { type: "STRING" },
    },
    required: ["who", "emoji", "text"],
    propertyOrdering: ["who", "emoji", "text"],
  };
  return {
    type: "OBJECT",
    properties: {
      headline: { type: "STRING" },
      summary: { type: "STRING" },
      today: { type: "ARRAY", items: item },
      ahead: { type: "ARRAY", items: item },
    },
    required: ["headline", "summary", "today", "ahead"],
    propertyOrdering: ["headline", "summary", "today", "ahead"],
  };
}

// Remove Markdown emphasis/bullets the model might still add.
export function cleanText(value: string, maxLength: number): string {
  const cleaned = value
    .replace(/\*\*|__|`/g, "")
    .replace(/^\s*[-*•]\s+/gm, "")
    .replace(/\s+/g, " ")
    .trim();
  return cleaned.length > maxLength
    ? `${cleaned.slice(0, maxLength - 1).trimEnd()}…`
    : cleaned;
}

function firstGrapheme(value: string): string {
  const trimmed = value.trim();
  if (trimmed === "") {
    return "•";
  }
  const Segmenter = (
    Intl as unknown as {
      Segmenter?: new (
        locale: string,
        options: { granularity: "grapheme" },
      ) => { segment: (input: string) => Iterable<{ segment: string }> };
    }
  ).Segmenter;
  if (Segmenter !== undefined) {
    for (const part of new Segmenter("de", { granularity: "grapheme" }).segment(
      trimmed,
    )) {
      return part.segment;
    }
  }
  return Array.from(trimmed)[0] ?? "•";
}

function parseItems(value: unknown, slugs: string[]): BriefingItem[] {
  if (!Array.isArray(value)) {
    return [];
  }
  const items: BriefingItem[] = [];
  for (const entry of value) {
    if (typeof entry !== "object" || entry === null) {
      continue;
    }
    const record = entry as Record<string, unknown>;
    if (typeof record.text !== "string") {
      continue;
    }
    const text = cleanText(record.text, 160);
    if (text === "") {
      continue;
    }
    const who =
      typeof record.who === "string" && slugs.includes(record.who.toLowerCase())
        ? record.who.toLowerCase()
        : FAMILY_WHO;
    const emoji =
      typeof record.emoji === "string" ? firstGrapheme(record.emoji) : "•";
    items.push({ who, emoji, text });
    if (items.length >= MAX_ITEMS) {
      break;
    }
  }
  return items;
}

/**
 * Parse and sanitise the model's JSON text. Throws a German error message
 * when the answer is unusable (so the UI can show it).
 */
export function parseBriefingResponse(
  raw: string,
  slugs: string[],
): ParsedBriefing {
  let data: unknown;
  try {
    // Tolerate a ```json fence around the payload.
    data = JSON.parse(raw.replace(/^\s*```(?:json)?\s*|\s*```\s*$/g, ""));
  } catch {
    throw new Error("Die KI-Antwort war kein gültiges JSON.");
  }
  if (typeof data !== "object" || data === null) {
    throw new Error("Die KI-Antwort hatte ein unerwartetes Format.");
  }
  const record = data as Record<string, unknown>;
  const headline =
    typeof record.headline === "string" ? cleanText(record.headline, 80) : "";
  const summary =
    typeof record.summary === "string" ? cleanText(record.summary, 400) : "";
  const today = parseItems(record.today, slugs);
  const ahead = parseItems(record.ahead, slugs);
  if (headline === "" && summary === "" && today.length === 0) {
    throw new Error("Die KI-Antwort war leer.");
  }
  return {
    headline: headline === "" ? "Euer Tag im Überblick" : headline,
    summary,
    today,
    ahead,
  };
}

/** Pull the text out of a generateContent response body. */
export function extractCandidateText(body: unknown): string {
  const candidates = (body as { candidates?: unknown }).candidates;
  if (!Array.isArray(candidates) || candidates.length === 0) {
    const blocked = (body as { promptFeedback?: { blockReason?: string } })
      .promptFeedback?.blockReason;
    throw new Error(
      blocked !== undefined
        ? `Die KI hat die Anfrage abgelehnt (${blocked}).`
        : "Die KI hat keine Antwort geliefert.",
    );
  }
  const parts = (
    candidates[0] as {
      content?: { parts?: { text?: unknown; thought?: unknown }[] };
    }
  ).content?.parts;
  // Skip "thought" parts of thinking models; only the answer counts.
  const text = (parts ?? [])
    .filter((part) => part.thought !== true)
    .map((part) => (typeof part.text === "string" ? part.text : ""))
    .join("");
  if (text.trim() === "") {
    throw new Error("Die KI hat keine Antwort geliefert.");
  }
  return text;
}
